### ISSUE TITLE
Вылет при клике на несколько фильтров

### ISSUE THREAD

**Issue by vaimon** [pedevyat/RussTravel#10]
Если покликать о фильтрам, приложение намертво зависает, после чего вылетает с ошибкой:
<img width="655" alt="image" src="https://github.com/pedevyat/RussTravel/assets/28728097/becf8528-25e8-413d-afc9-85b83b1419a7">

**Comment by MihaxXx** [comment]
@vaimon Это, видимо, что-то в сторону #4

**Comment by MihailPohodeev** [comment]
Больше не вылетает. Исправлено

**Comment by MihailPohodeev** [comment]
commit - 8b76704
