### ISSUE TITLE
При выборе фильтра на карте система объединения точек сходит с ума

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#11]
Выбираем музеи, карта чуть двигается и вот пожалуйста, всего две точки, пока не увеличишь
<details>

![image](https://github.com/pedevyat/RussTravel/assets/5885676/1dee70d6-d5b7-4a73-90bd-498e017ade09)

![image](https://github.com/pedevyat/RussTravel/assets/5885676/006b6f00-6bc7-428c-b8a3-48062a31b10e)
</details>

**Comment by pedevyat** [comment]
Сменили карту. При тестировании такое не наблюдалось

**Comment by MihaxXx** [comment]
Коммит/PR?

**Comment by pedevyat** [comment]
8b76704
537f200c33879e255ddfa96105b9cf9b08b17748
