### ISSUE TITLE
Не дублировать поиск в статьях

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#12]
Нет никакого смысла при наличии поля вводе делать ещё и диалог
<details>

![image](https://github.com/pedevyat/RussTravel/assets/5885676/bf73254e-2c01-47f6-96bc-9733a29e9f04)
</details>

**Comment by pedevyat** [comment]
Убрано.

**Comment by MihaxXx** [comment]
Коммит/PR?

**Comment by pedevyat** [comment]
1ff1140
