### ISSUE TITLE
Не работает определение местоположения

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#13]
Даже если дать доступ через настройки, карты всегда открывается с минимальным масштабом

**Comment by pedevyat** [comment]
Добавлено

**Comment by MihaxXx** [comment]
Коммит/PR?

**Comment by pedevyat** [comment]
ecd58f6
(изначально подразумевалось, что функция не работает, но оказалось наоборот)

**Comment by MihaxXx** [comment]
Безумно красноречивый commit message
