### ISSUE TITLE
Некорректное поведение при повороте экрана

### ISSUE THREAD

**Issue by vaimon** [pedevyat/RussTravel#3]
Поворот экрана ломает вёрстку на некоторых фрагментах:
![image](https://github.com/pedevyat/RussTravel/assets/28728097/fb9fe218-a48f-46a2-a346-691dadff9f02)
![image](https://github.com/pedevyat/RussTravel/assets/28728097/08781ba1-d192-471b-af02-8e4a14686571)

**Comment by MihailPohodeev** [comment]
Баг исправлен

**Comment by MihailPohodeev** [comment]
коммит 67ad5f9
