### ISSUE TITLE
Падение при повторном открытии карты после перехода на др. вкладку

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#4]
Кейс:
- Открываем вкладку Карта
- Не дожидаясь завершения загрузки, переходим на другую вкладку
- Возвращаемся на Карту
- Ждём пару десятков секунд и приложении падает в попытке загрузить карту

Девайс: Google Pixel 5a 5G, Android 14

**Comment by MihaxXx** [comment]
Стало получше, но из-за долго загрузки, которая ставит всё на паузу, всё ещё можно добиться падения приложения на запуске

**Comment by MihailPohodeev** [comment]
Исправлено

**Comment by MihailPohodeev** [comment]
commit 8b76704
