### ISSUE TITLE
Добавить спинеры при длительной загрузке

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#5]
Добавить спинеры в местах, где происходит длительная загрузка, чтобы показать пользователю, что приложение не зависло

**Comment by MihaxXx** [comment]
Почему не сделали?

**Comment by pedevyat** [comment]
Мы добавляли спинер в код, но он не срабатывал в тех местах, где надо. Будем переделывать.

**Comment by MihailPohodeev** [comment]
спиннеры добавлены в места длительной загрузки

**Comment by MihailPohodeev** [comment]
коммит для спиннеров на карте - 8e76f30
коммит для спиннеров для страниц профиля - 05a6be9
