### ISSUE TITLE
Указать типы полей ввода

### ISSUE THREAD

**Issue by MihaxXx** [pedevyat/RussTravel#6]
Для полей можно указать тип вводимой информации (почта, пароль, имя итд), чтобы клавиатура подстроилась, например, показала на основной панели символ @

**Comment by MihaxXx** [comment]
Исправили выпиливанием функционала совсем?

**Comment by MihailPohodeev** [comment]
Вернули и настроили

**Comment by MihailPohodeev** [comment]
commit 0355eb6
