### ISSUE TITLE
Обратная связь рри добавлении в избранное

### ISSUE THREAD

**Issue by vaimon** [pedevyat/RussTravel#8]
Нет никакой обратной связи при нажатии кнопки со звёздочкой на карточке на карте. Не особо понятно: работает ли она вообще или нет.

**Comment by MihaxXx** [comment]
Как? Ничего не происходит, значит, не работает!

**Comment by MihailPohodeev** [comment]
Обратная связь настроена. Теперь появляется всплывающее сообщение при добавлении и удалении достопримечательности.

**Comment by MihailPohodeev** [comment]
commit - 2ef317c
