### ISSUE TITLE
Фризы ри работе с картой

### ISSUE THREAD

**Issue by vaimon** [pedevyat/RussTravel#9]
Карта заметно фризит UI при загрузке данных. При этом любое взаимодействие с фильтрами возвращает её в исходное состояние и всё так же фризит. Вы точно ничего лишнего не делаете в UI-потоке?

**Comment by MihailPohodeev** [comment]
Исправлено

**Comment by MihailPohodeev** [comment]
yandex maps были заменены на osm.
commit - 8b76704
